version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Checking environment..."
      - node -v
      - npm -v
      - echo "Installing dependencies (including dev)..."
      - export NODE_ENV=development
      - npm install
  pre_build:
    commands:
      - echo "Running tests..."
      - npm test
  build:
    commands:
      - echo Build started on `date`
      - # npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - index.js
    - package.json
    - package-lock.json
    - public/**/*
    - .ebextensions/**/*
    - .platform/**/*
    - Procfile
  # Do not include node_modules here; Elastic Beanstalk will run 'npm install' on the server

